const INGREDIENT_MAP = {
  'avocado': { ar: 'أفوكادو', tr: 'Avokado', ru: 'Авокадо', zh: '牛油果' },
  'avocado maki': { ar: 'أفوكادو ماكي', tr: 'Avokado maki', ru: 'Авокадо маки', zh: '牛油果细卷' },
  'avocado sake maki': { ar: 'أفوكادو ساكي ماكي', tr: 'Avokado sake maki', ru: 'Авокадо сакэ маки', zh: '牛油果三文鱼细卷' },
  'baby corn': { ar: 'ذرة صغيرة', tr: 'Baby mısır', ru: 'Мини-кукуруза', zh: '玉米笋' },
  'banana': { ar: 'موز', tr: 'Muz', ru: 'Банан', zh: '香蕉' },
  'bean sprouts': { ar: 'براعم الصويا', tr: 'Soya filizi', ru: 'Ростки сои', zh: '豆芽' },
  'beef': { ar: 'لحم بقري', tr: 'Dana eti', ru: 'Говядина', zh: '牛肉' },
  'bell pepper': { ar: 'فلفل حلو', tr: 'Dolmalık biber', ru: 'Болгарский перец', zh: '甜椒' },
  'broccoli': { ar: 'بروكلي', tr: 'Brokoli', ru: 'Брокколи', zh: '西蓝花' },
  'cabbage': { ar: 'ملفوف', tr: 'Lahana', ru: 'Капуста', zh: '卷心菜' },
  'calamari': { ar: 'كالاماري', tr: 'Kalamar', ru: 'Кальмар', zh: '鱿鱼' },
  'calamari tempura': { ar: 'تمبورا كالاماري', tr: 'Kalamar tempura', ru: 'Кальмар темпура', zh: '鱿鱼天妇罗' },
  'calamari tempura roll': { ar: 'رول كالاماري تمبورا', tr: 'Kalamar tempura roll', ru: 'Ролл кальмар темпура', zh: '鱿鱼天妇罗卷' },
  'california': { ar: 'كاليفورنيا', tr: 'California', ru: 'Калифорния', zh: '加州卷' },
  'california roll': { ar: 'رول كاليفورنيا', tr: 'California roll', ru: 'Ролл Калифорния', zh: '加州卷' },
  'caramel color': { ar: 'لون كراميل', tr: 'Karamel renklendirici', ru: 'Карамельный колер', zh: '焦糖色' },
  'carbonated water': { ar: 'مياه غازية', tr: 'Gazlı su', ru: 'Газированная вода', zh: '碳酸水' },
  'carrot': { ar: 'جزر', tr: 'Havuç', ru: 'Морковь', zh: '胡萝卜' },
  'chicken': { ar: 'دجاج', tr: 'Tavuk', ru: 'Курица', zh: '鸡肉' },
  'chicken california roll': { ar: 'رول دجاج كاليفورنيا', tr: 'Tavuklu california roll', ru: 'Куриный ролл Калифорния', zh: '鸡肉加州卷' },
  'chicken maki': { ar: 'دجاج ماكي', tr: 'Tavuklu maki', ru: 'Куриный маки', zh: '鸡肉细卷' },
  'chicken philadelphia roll': { ar: 'رول دجاج فيلادلفيا', tr: 'Tavuklu philadelphia roll', ru: 'Куриный ролл Филадельфия', zh: '鸡肉费城卷' },
  'chicken tempura roll': { ar: 'رول دجاج تمبورا', tr: 'Tavuk tempura roll', ru: 'Куриный ролл темпура', zh: '鸡肉天妇罗卷' },
  'chili': { ar: 'فلفل حار', tr: 'Acı biber', ru: 'Чили', zh: '辣椒' },
  'chili flakes': { ar: 'رقائق فلفل حار', tr: 'Pul biber', ru: 'Хлопья чили', zh: '辣椒碎' },
  'chili sauce': { ar: 'صوص فلفل حار', tr: 'Acı sos', ru: 'Соус чили', zh: '辣酱' },
  'cilantro': { ar: 'كزبرة', tr: 'Kişniş', ru: 'Кинза', zh: '香菜' },
  'corn': { ar: 'ذرة', tr: 'Mısır', ru: 'Кукуруза', zh: '玉米' },
  'crab': { ar: 'سلطعون', tr: 'Yengeç', ru: 'Краб', zh: '蟹肉' },
  'crab tempura': { ar: 'تمبورا سلطعون', tr: 'Yengeç tempura', ru: 'Краб темпура', zh: '蟹肉天妇罗' },
  'crazy salmon': { ar: 'كريزي سلمون', tr: 'Crazy salmon', ru: 'Крейзи лосось', zh: '疯狂三文鱼' },
  'crazy tuna': { ar: 'كريزي تونة', tr: 'Crazy tuna', ru: 'Крейзи тунец', zh: '疯狂金枪鱼' },
  'cream cheese': { ar: 'جبن كريمي', tr: 'Krem peynir', ru: 'Сливочный сыр', zh: '奶油奶酪' },
  'crispy chicken': { ar: 'دجاج مقرمش', tr: 'Çıtır tavuk', ru: 'Хрустящая курица', zh: '香脆鸡肉' },
  'crispy crunchy california': { ar: 'كرانشي مقرمش كاليفورنيا', tr: 'Çıtır crunchy california', ru: 'Хрустящий ролл Калифорния', zh: '香脆加州卷' },
  'crispy crunchy ebi ten': { ar: 'كرانشي مقرمش إيبي تن', tr: 'Çıtır crunchy ebi ten', ru: 'Хрустящий эби тэн', zh: '香脆炸虾天妇罗' },
  'crispy crunchy philadelphia': { ar: 'كرانشي مقرمش فيلادلفيا', tr: 'Çıtır crunchy philadelphia', ru: 'Хрустящий ролл Филадельфия', zh: '香脆费城卷' },
  'cucumber': { ar: 'خيار', tr: 'Salatalık', ru: 'Огурец', zh: '黄瓜' },
  'curry powder': { ar: 'مسحوق كاري', tr: 'Köri tozu', ru: 'Порошок карри', zh: '咖喱粉' },
  'dipping sauce': { ar: 'صوص التغميس', tr: 'Dip sos', ru: 'Соус для макания', zh: '蘸酱' },
  'dragon roll': { ar: 'دراغون رول', tr: 'Dragon roll', ru: 'Дракон-ролл', zh: '龙卷' },
  'dynamite chicken roll': { ar: 'رول دجاج ديناميت', tr: 'Dinamit tavuk roll', ru: 'Куриный ролл динамит', zh: '炸弹鸡肉卷' },
  'dynamite karides roll': { ar: 'رول روبيان ديناميت', tr: 'Dinamit karides roll', ru: 'Ролл динамит с креветками', zh: '炸弹虾卷' },
  'dynamite sauce': { ar: 'صوص ديناميت', tr: 'Dinamit sosu', ru: 'Соус динамит', zh: '炸弹酱' },
  'ebi maki': { ar: 'إيبي ماكي', tr: 'Ebi maki', ru: 'Эби-маки', zh: '炸虾细卷' },
  'ebi tempura roll': { ar: 'رول إيبي تمبورا', tr: 'Ebi tempura roll', ru: 'Ролл эби темпура', zh: '炸虾天妇罗卷' },
  'edamame': { ar: 'إدامامي', tr: 'Edamame', ru: 'Эдамаме', zh: '毛豆' },
  'eel': { ar: 'أنقليس', tr: 'Yılan balığı', ru: 'Угорь', zh: '鳗鱼' },
  'egg': { ar: 'بيض', tr: 'Yumurta', ru: 'Яйцо', zh: '鸡蛋' },
  'egg yolk': { ar: 'صفار البيض', tr: 'Yumurta sarısı', ru: 'Яичный желток', zh: '蛋黄' },
  'fresh salmon': { ar: 'سلمون طازج', tr: 'Taze somon', ru: 'Свежий лосось', zh: '鲜三文鱼' },
  'fried calamari': { ar: 'كالاماري مقلي', tr: 'Kızarmış kalamar', ru: 'Жареный кальмар', zh: '炸鱿鱼' },
  'fried shrimp': { ar: 'روبيان مقلي', tr: 'Kızarmış karides', ru: 'Жареные креветки', zh: '炸虾' },
  'galangal': { ar: 'خولنجان', tr: 'Havlıcan', ru: 'Галангал', zh: '高良姜' },
  'garlic': { ar: 'ثوم', tr: 'Sarımsak', ru: 'Чеснок', zh: '大蒜' },
  'garlic sauce': { ar: 'صوص الثوم', tr: 'Sarımsak sosu', ru: 'Чесночный соус', zh: '蒜蓉酱' },
  'general tso chicken': { ar: 'دجاج جنرال تسو', tr: 'General TSO tavuk', ru: 'Курица Генерала Цо', zh: '左宗棠鸡' },
  'general tso sauce': { ar: 'صوص جنرال تسو', tr: 'General TSO sosu', ru: 'Соус Генерала Цо', zh: '左宗棠酱' },
  'ginger': { ar: 'زنجبيل', tr: 'Zencefil', ru: 'Имбирь', zh: '生姜' },
  'green pepper': { ar: 'فلفل أخضر', tr: 'Yeşil biber', ru: 'Зелёный перец', zh: '青椒' },
  'honey': { ar: 'عسل', tr: 'Bal', ru: 'Мёд', zh: '蜂蜜' },
  'ice cream': { ar: 'آيس كريم', tr: 'Dondurma', ru: 'Мороженое', zh: '冰淇淋' },
  'kaffir lime leaf': { ar: 'أوراق ليمون كافير', tr: 'Kaffir misket limonu yaprağı', ru: 'Листья кафрского лайма', zh: '青柠叶' },
  'kani maki': { ar: 'كاني ماكي', tr: 'Kani maki', ru: 'Кани-маки', zh: '蟹肉细卷' },
  'kani maki roll': { ar: 'رول كاني ماكي', tr: 'Kani maki roll', ru: 'Кани-маки ролл', zh: '蟹肉细卷' },
  'kappa maki': { ar: 'كابا ماكي', tr: 'Kappa maki', ru: 'Каппа-маки', zh: '黄瓜细卷' },
  'lemongrass': { ar: 'عشبة الليمون', tr: 'Limon otu', ru: 'Лемонграсс', zh: '柠檬草' },
  'mayo': { ar: 'مايونيز', tr: 'Mayonez', ru: 'Майонез', zh: '蛋黄酱' },
  'minced beef': { ar: 'لحم بقري مفروم', tr: 'Kıyma dana eti', ru: 'Говяжий фарш', zh: '牛肉糜' },
  'minced meat': { ar: 'لحم مفروم', tr: 'Kıyma', ru: 'Мясной фарш', zh: '肉糜' },
  'miso': { ar: 'ميسو', tr: 'Miso', ru: 'Мисо', zh: '味噌' },
  'mixed seafood': { ar: 'مأكولات بحرية مشكلة', tr: 'Karışık deniz mahsulleri', ru: 'Морепродукты ассорти', zh: '什锦海鲜' },
  'mixed vegetables': { ar: 'خضروات مشكلة', tr: 'Karışık sebzeler', ru: 'Овощи ассорти', zh: '什锦蔬菜' },
  'mushroom': { ar: 'فطر', tr: 'Mantar', ru: 'Грибы', zh: '蘑菇' },
  'noodles': { ar: 'نودلز', tr: 'Noodle', ru: 'Лапша', zh: '面条' },
  'nori': { ar: 'أعشاب نوري', tr: 'Nori', ru: 'Нори', zh: '海苔' },
  'nutella': { ar: 'نوتيلا', tr: 'Nutella', ru: 'Нутелла', zh: '能多益' },
  'onion': { ar: 'بصل', tr: 'Soğan', ru: 'Лук', zh: '洋葱' },
  'orange juice': { ar: 'عصير برتقال', tr: 'Portakal suyu', ru: 'Апельсиновый сок', zh: '橙汁' },
  'osaka roll': { ar: 'أوساكا رول', tr: 'Osaka roll', ru: 'Ролл Осака', zh: '大阪卷' },
  'oyster sauce': { ar: 'صوص المحار', tr: 'İstiridye sosu', ru: 'Устричный соус', zh: '蚝油' },
  'panko': { ar: 'بانكو', tr: 'Panko', ru: 'Панко', zh: '面包糠' },
  'peanuts': { ar: 'فول سوداني', tr: 'Fıstık', ru: 'Арахис', zh: '花生' },
  'peas': { ar: 'بازلاء', tr: 'Bezelye', ru: 'Горошек', zh: '豌豆' },
  'pepper': { ar: 'فلفل', tr: 'Biber', ru: 'Перец', zh: '胡椒' },
  'philadelphia': { ar: 'فيلادلفيا', tr: 'Philadelphia', ru: 'Филадельфия', zh: '费城卷' },
  'philadelphia roll': { ar: 'رول فيلادلفيا', tr: 'Philadelphia roll', ru: 'Ролл Филадельфия', zh: '费城卷' },
  'pickled vegetables': { ar: 'خضروات مخللة', tr: 'Turşu sebzeler', ru: 'Маринованные овощи', zh: '腌菜' },
  'pineapple': { ar: 'أناناس', tr: 'Ananas', ru: 'Ананас', zh: '菠萝' },
  'pork/beef': { ar: 'لحم بقري', tr: 'Dana eti', ru: 'Говядина', zh: '牛肉' },
  'prawn': { ar: 'روبيان', tr: 'Karides', ru: 'Креветки', zh: '对虾' },
  'ramen noodles': { ar: 'نودلز رامن', tr: 'Ramen noodle', ru: 'Лапша рамен', zh: '拉面面条' },
  'red cabbage': { ar: 'ملفوف أحمر', tr: 'Kırmızı lahana', ru: 'Красная капуста', zh: '红甘蓝' },
  'rice': { ar: 'أرز', tr: 'Pirinç', ru: 'Рис', zh: '米饭' },
  'rice noodles': { ar: 'نودلز الأرز', tr: 'Pirinç eriştesi', ru: 'Рисовая лапша', zh: '米粉' },
  'rice vinegar': { ar: 'خل الأرز', tr: 'Pirinç sirkesi', ru: 'Рисовый уксус', zh: '米醋' },
  'sake maki': { ar: 'ساكي ماكي', tr: 'Sake maki', ru: 'Сакэ-маки', zh: '三文鱼细卷' },
  'sake maki roll': { ar: 'رول ساكي ماكي', tr: 'Sake maki roll', ru: 'Сакэ-маки ролл', zh: '三文鱼细卷' },
  'salmon': { ar: 'سلمون', tr: 'Somon', ru: 'Лосось', zh: '三文鱼' },
  'salmon tempura': { ar: 'تمبورا سلمون', tr: 'Somon tempura', ru: 'Лосось темпура', zh: '三文鱼天妇罗' },
  'salmon tempura roll': { ar: 'رول سلمون تمبورا', tr: 'Somon tempura roll', ru: 'Ролл лосось темпура', zh: '三文鱼天妇罗卷' },
  'salmon ten roll': { ar: 'رول سلمون تن', tr: 'Salmon ten roll', ru: 'Ролл лосось тэн', zh: '三文鱼天妇罗卷' },
  'scallions': { ar: 'بصل أخضر', tr: 'Taze soğan', ru: 'Зелёный лук', zh: '小葱' },
  'sea bass': { ar: 'قاروص', tr: 'Levrek', ru: 'Сибас', zh: '鲈鱼' },
  'seaweed': { ar: 'أعشاب بحرية', tr: 'Deniz yosunu', ru: 'Морские водоросли', zh: '海藻' },
  'sesame': { ar: 'سمسم', tr: 'Susam', ru: 'Кунжут', zh: '芝麻' },
  'shrimp': { ar: 'روبيان', tr: 'Karides', ru: 'Креветки', zh: '虾仁' },
  'shrimp bites': { ar: 'قطع روبيان', tr: 'Karides topları', ru: 'Шарики из креветок', zh: '虾球' },
  'shrimp tempura': { ar: 'تمبورا روبيان', tr: 'Karides tempura', ru: 'Креветки темпура', zh: '虾天妇罗' },
  'smoked salmon': { ar: 'سلمون مدخن', tr: 'Tütsülenmiş somon', ru: 'Копчёный лосось', zh: '烟熏三文鱼' },
  'soy sauce': { ar: 'صوص الصويا', tr: 'Soya sosu', ru: 'Соевый соус', zh: '酱油' },
  'spicy dynamite sauce': { ar: 'صوص ديناميت حار', tr: 'Acılı dinamit sosu', ru: 'Острый соус динамит', zh: '香辣炸弹酱' },
  'spicy mayo': { ar: 'مايونيز حار', tr: 'Acılı mayonez', ru: 'Острый майонез', zh: '香辣蛋黄酱' },
  'spicy tuna maki': { ar: 'سبايسي تونة ماكي', tr: 'Spicy tuna maki', ru: 'Спайси тунец-маки', zh: '辣金枪鱼细卷' },
  'spring onion': { ar: 'بصل أخضر', tr: 'Taze soğan', ru: 'Зелёный лук', zh: '葱花' },
  'spring rolls': { ar: 'سبرينغ رولز', tr: 'Sigara böreği / Spring rolls', ru: 'Спринг-роллы', zh: '春卷' },
  'steamed rice': { ar: 'أرز على البخار', tr: 'Buharda pirinç', ru: 'Рис на пару', zh: '蒸米饭' },
  'sweet chili sauce': { ar: 'صوص تشيلي حلو', tr: 'Tatlı acı sos', ru: 'Сладкий соус чили', zh: '甜辣酱' },
  'sweet corn': { ar: 'ذرة حلوة', tr: 'Tatlı mısır', ru: 'Сладкая кукуруза', zh: '甜玉米' },
  'sweet sour sauce': { ar: 'صوص حلو وحامض', tr: 'Tatlı ekşi sos', ru: 'Кисло-сладкий соус', zh: '甜酸酱' },
  'teriyaki': { ar: 'تيرياكي', tr: 'Teriyaki', ru: 'Терияки', zh: '照烧' },
  'teriyaki sauce': { ar: 'صوص تيرياكي', tr: 'Teriyaki sosu', ru: 'Соус терияки', zh: '照烧酱' },
  'tobiko': { ar: 'توبيكو', tr: 'Tobiko', ru: 'Тобико', zh: '飞鱼籽' },
  'tofu': { ar: 'توفو', tr: 'Tofu', ru: 'Тофу', zh: '豆腐' },
  'tomato': { ar: 'طماطم', tr: 'Domates', ru: 'Помидоры', zh: '番茄' },
  'tuna': { ar: 'تونة', tr: 'Tuna balığı', ru: 'Тунец', zh: '金枪鱼' },
  'udon noodles': { ar: 'نودلز أودون', tr: 'Udon eriştesi', ru: 'Лапша удон', zh: '乌冬面' },
  'vegan roll': { ar: 'رول نباتي', tr: 'Vegan roll', ru: 'Веганский ролл', zh: '纯素卷' },
  'vegetables': { ar: 'خضروات', tr: 'Sebzeler', ru: 'Овощи', zh: '蔬菜' },
  'wakame': { ar: 'واكامي', tr: 'Wakame', ru: 'Вакамэ', zh: '裙带菜' },
  'walnut': { ar: 'جوز', tr: 'Ceviz', ru: 'Грецкий орех', zh: '核桃' },
  'wasabi': { ar: 'واسابي', tr: 'Wasabi', ru: 'Васаби', zh: '青芥末' },
  'white cabbage': { ar: 'ملفوف أبيض', tr: 'Beyaz lahana', ru: 'Белокочанная капуста', zh: '白甘蓝' },
  'zucchini': { ar: 'كوسا', tr: 'Kabak', ru: 'Кабачок', zh: '西葫芦' }
};

export function translateIngredient(ing, lang) {
  if (!ing) return '';
  const key = ing.trim().toLowerCase();
  if (lang === 'en') return ing;
  if (INGREDIENT_MAP[key] && INGREDIENT_MAP[key][lang]) {
    return INGREDIENT_MAP[key][lang];
  }
  return ing;
}

export function translateIngredientsList(ingredients, lang) {
  if (!Array.isArray(ingredients)) return '';
  const sep = lang === 'ar' || lang === 'zh' ? ' · ' : ' · ';
  return ingredients.map(i => translateIngredient(i, lang)).filter(Boolean).join(sep);
}
